version: "3.9"

services:
  db:
    image: postgres:12.4
    restart: unless-stopped
    container_name: db
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/posgresql/data

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  portainer:
    image: portainer/portainer
    restart: always
    ports:
      - "9000:9000"
    container_name: portainer
    depends_on:
      - db
      - django
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  django:
    container_name: django_app
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
volumes:
  pgdata:
  portainer_data: {}
