# Generated by Django 4.0.3 on 2022-03-12 21:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0004_movie_downvotes_movie_upvotes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('movie', 'user')},
        ),
    ]
