# Generated by Django 4.0.3 on 2022-03-13 10:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_vote_movie_alter_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
